# For travis use user id 2000
language: shell
os: linux
dist: xenial
env:
  DOCKER_COMPOSE_VERSION: 1.4.2
  global:
    - CC_TEST_REPORTER_ID=fcccb2678486786b2076f6a4744683837be23b89bcff990be727793a449b1447

services:
  - docker

before_install:
  - docker run --rm -v $(pwd):/app composer install
  - sudo chown -R $USER:$USER ./
  - cp .env.travis .env
  - cp docker-compose.travis.yml docker-compose.yml
  - docker-compose up -d
  - docker-compose ps
  - docker-compose exec app php artisan key:generate
  - docker-compose exec app php artisan config:clear
  - docker-compose exec app php artisan route:clear
  - docker-compose exec app php artisan cache:clear
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
  - sleep 15

script:
  - docker-compose exec app php artisan migrate
  - docker-compose exec app php artisan db:seed
  - docker-compose exec app vendor/bin/phpcs --standard=phpcs.xml ./
  - docker-compose exec app vendor/bin/phpmd app,config,resources,routes,tests ansi phpmd.xml
  - docker-compose exec app php -d memory_limit=2G vendor/bin/phpstan analyse -c phpstan.neon
  - docker-compose exec -T db mysql -uroot  <<< "create database sm_semec_test;"
  - docker-compose exec -T db mysql -uroot  <<< "CREATE USER 'sm-semec'@'localhost' IDENTIFIED BY 'sm-semec';"
  - docker-compose exec -T db mysql -uroot  <<< "GRANT ALL ON sm_semec_test.* TO 'sm-semec'@'%' IDENTIFIED BY 'sm-semec'; FLUSH PRIVILEGES;"
  - docker-compose exec -T db mysql -usm-semec -psm-semec  <<< "show databases;"
  - docker-compose exec app npm install
  - docker-compose exec app npm run dev
  - docker-compose exec app php artisan migrate:refresh --env=testing
  - docker-compose exec app php artisan test
  - docker-compose exec app php artisan dusk

after_script:
  - sed -i 's?/var/www?'`pwd`'?' clover.xml
  - export CC_TEST_REPORTER_ID=fcccb2678486786b2076f6a4744683837be23b89bcff990be727793a449b1447 && ./cc-test-reporter after-build -p /home/travis/build/utfpr-gp-tsi/sm-semec/ -t clover --exit-code $TRAVIS_TEST_RESULT
