name: CI
on:
  pull_request_target:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - master
      
jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          extensions: curl, dom, fileinfo, filter, iconv, json, libxml, mbstring, openssl, pcntl, pcre, pdo, simplexml, tokenizer, xml, xmlwriter, zip, pdo_mysql
          tools: composer:v2

      - name: Install composer dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist

      - name: Code analyse by PHPCS
        run: |
          vendor/bin/phpcs --standard=phpcs.xml ./

      - name: Code analyse by PHPMD
        run: |
          vendor/bin/phpmd app,config,resources,routes,tests ansi phpmd.xml

      - name: Code analyse by PHPSTAN
        run: |
          php -d memory_limit=3G vendor/bin/phpstan analyse -c phpstan.neon
  units:
    runs-on: ubuntu-latest
    environment: testing
    env:
      DB_HOST: 127.0.0.1
      DB_PORT: 3306
    services:
      db:
        image: mysql:8.0.23
        env:
          MYSQL_DATABASE: sm_semec
          MYSQL_USER: sm-semec
          MYSQL_PASSWORD: sm-semec
          MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
        ports:
          - 3306:3306
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          extensions: curl, dom, fileinfo, filter, iconv, json, libxml, mbstring, openssl, pcntl, pcre, pdo, simplexml, tokenizer, xml, xmlwriter, zip, pdo_mysql
          tools: composer:v2

      - name: Install composer dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist

      - name: Prepare .env
        run: |
          cp .env.ci .env
          echo "
          APP_NAME=Laravel_Testing
          APP_ENV=testing
          APP_KEY=base64:nxo8OJOYZ9YyRtlpv8kWwNXcY0YO4Z4kolja1Z4ZxV4=
          APP_DEBU=false
          APP_URL=http://localhost
          DB_CONNECTION=mysql
          DB_HOST=db
          DB_PORT=3306
          DB_DATABASE=sm_semec_test
          DB_USERNAME=sm-semec
          DB_PASSWORD=sm-semec
          MAIL_FROM_ADDRESS=${{ vars.MAIL_FROM_ADDRESS }}
          MAIL_FROM_NAME=${{ vars.MAIL_FROM_NAME }}
          MAIL_USERNAME=${{ secrets.MAIL_USERNAME }}
          MAIL_PASSWORD=${{ secrets.MAIL_PASSWORD }}
          MAIL_ENCRYPTION=${{ vars.MAIL_ENCRYPTION }}
          MAIL_DRIVER=${{ vars.DRIVER }}
          MAIL_HOST=${{ vars.MAIL_HOST }}
          MAIL_PORT=${{ vars.MAIL_PORT }}
          " > .env.testing

      - name: Clear all cache
        run: |
          php artisan key:generate
          php artisan config:clear
          php artisan route:clear
          php artisan cache:clear

      - name: Link storage folder
        run: |
          php artisan storage:link

      - name: Migration the database
        run: |
          mysql -h 127.0.0.1 --port 3306 -u root -e "show databases;"
          php artisan migrate
          php artisan db:seed

      - name: Migrate on test env
        run: |
          docker exec ${{ job.services.db.id }} mysql -e "GRANT ALL PRIVILEGES ON *.* TO 'sm-semec'@'%' WITH GRANT OPTION;"
          docker exec ${{ job.services.db.id }} mysql -u sm-semec -psm-semec -e "CREATE DATABASE sm_semec_test; SHOW DATABASES;"
          php artisan migrate --env=testing

      - name: Run units tests
        run: |
          php artisan test

  dusks:
    runs-on: ubuntu-latest
    environment: testing
    services:
      webserver:
        image: nginx:alpine
        volumes:
          - /var/www/:/var/www/
          - /var/www/nginx/conf.d/dev/:/etc/nginx/conf.d/
        ports:
          - 80:80
      db:
        image: mysql:8.0.23
        env:
          MYSQL_DATABASE: sm_semec_test
          MYSQL_USER: sm-semec
          MYSQL_PASSWORD: sm-semec
          MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
        ports:
          - 3306:3306
      selenium:
        image: selenium/standalone-chrome-debug:latest
        ports:
          - 4444:4444
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          extensions: curl, dom, fileinfo, filter, iconv, json, libxml, mbstring, openssl, pcntl, pcre, pdo, simplexml, tokenizer, xml, xmlwriter, zip, pdo_mysql
          tools: composer:v2

      - name: Setup php-fpm
        env:
          version: 8.1
        run: |
          sudo sed -i 's|listen = /run/php/php8.1-fpm.sock|listen = 0.0.0.0:9000|g' /etc/php/$version/fpm/pool.d/www.conf
          sudo service php$version-fpm restart
          sudo service php$version-fpm status

      - name: Change hostname
        run: |
          sudo hostname app
          docker exec ${{ job.services.webserver.id }} nc -zvw10 $(hostname) 9000

      - name: Install composer dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist

      - name: Prepare .env and .env.testing
        run: |
          cp .env.ci .env
          echo "
          APP_NAME=Laravel_Testing
          APP_ENV=testing
          APP_KEY=base64:nxo8OJOYZ9YyRtlpv8kWwNXcY0YO4Z4kolja1Z4ZxV4=
          APP_DEBU=false
          APP_URL=http://localhost
          DB_CONNECTION=mysql
          DB_HOST=db
          DB_PORT=3306
          DB_DATABASE=sm_semec_test
          DB_USERNAME=sm-semec
          DB_PASSWORD=sm-semec
          MAIL_FROM_ADDRESS=${{ vars.MAIL_FROM_ADDRESS }}
          MAIL_FROM_NAME=${{ vars.MAIL_FROM_NAME }}
          MAIL_USERNAME=${{ secrets.MAIL_USERNAME }}
          MAIL_PASSWORD=${{ secrets.MAIL_PASSWORD }}
          MAIL_ENCRYPTION=${{ vars.MAIL_ENCRYPTION }}
          MAIL_DRIVER=${{ vars.DRIVER }}
          MAIL_HOST=${{ vars.MAIL_HOST }}
          MAIL_PORT=${{ vars.MAIL_PORT }}
          " > .env.testing

      - name: Prepare .env.dusk.local
        run: |
          cp .env.dusk.local.example .env.dusk.local

          sed -i 's|DB_HOST=db|DB_HOST=app|g' .env.dusk.local

          # Setup email credetials
          sed -i '/MAIL*/d' .env.dusk.local
          echo "
          MAIL_FROM_ADDRESS=${{ vars.MAIL_FROM_ADDRESS }}
          MAIL_FROM_NAME=${{ vars.MAIL_FROM_NAME }}
          MAIL_USERNAME=${{ secrets.MAIL_USERNAME }}
          MAIL_PASSWORD=${{ secrets.MAIL_PASSWORD }}
          MAIL_ENCRYPTION=${{ vars.MAIL_ENCRYPTION }}
          MAIL_DRIVER=${{ vars.DRIVER }}
          MAIL_HOST=${{ vars.MAIL_HOST }}
          MAIL_PORT=${{ vars.MAIL_PORT }}
          " >> .env.dusk.local
          cat .env.dusk.local

      - name: Setup key and update chrome driver
        run: |
          php artisan dusk:chrome-driver
          php artisan key:generate

      - name: Clear all cache
        run: |
          php artisan config:clear
          php artisan route:clear
          php artisan cache:clear

      - uses: actions/setup-node@v3
        with:
          node-version: "18.14.2"

      - name: Install npm dependencies
        run: |
          npm install
          npm run production

      - name: Migrate test database
        run: |
          php artisan migrate:fresh --env=testing
        env:
          DB_HOST: 127.0.0.1
          DB_PORT: 3306

      - name: Copy files to /var/www
        run: |
          sudo cp -r . /var/www/
          # https://laracasts.com/discuss/channels/laravel/laravel-9-storage-permission
          # https://gist.github.com/muhozi/dadfdabbe7e83d7a97003bee23bbebbf
          sudo chown -R $USER:www-data /var/www
          sudo usermod -a -G www-data $USER
          sudo find /var/www -type f -exec chmod 664 {} \;
          sudo find /var/www -type d -exec chmod 775 {} \;

          docker restart ${{ job.services.webserver.id }}

      - name: Run dusk tests
        run: |
          cd /var/www
          php artisan storage:link
          php artisan dusk
        env:
          SELENIUM_HOST: app

      - name: Upload screenshots
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: screenshots
          path: /var/www/tests/Browser/screenshots

      - name: Upload console logs
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: console
          path: /var/www/tests/Browser/console

      - name: Upload laravel logs
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: laravel-logs
          path: /var/www/storage/logs
